mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path


from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    AboutMeUpdateView,
    ListUsersView,
    UserDetailsView,
)

app_name = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path(
        "about-me/<int:pk>/update/", AboutMeUpdateView.as_view(), name="update_about_me"
    ),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/", ListUsersView.as_view(), name="list_user"),
    path("users/<int:pk>/", UserDetailsView.as_view(), name="user_details"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic.base import TemplateView
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from rest_framework.routers import DefaultRouter
from shopapp.views import (
    ProductViewSet,
    OrderViewSet,
)
from .sitemaps import sitemaps

router = DefaultRouter()
router.register("products", ProductViewSet)
router.register("orders", OrderViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shop/", include("shopapp.urls")),
    path("myauth/", include("myauth.urls")),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="docs"),
    # path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/", include(router.urls)),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path(
            "__debug__/",
            include(debug_toolbar.urls),
        )
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    ProductDetailsView,
    ProductsListView,
    OrdersListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    ProductViewSet,
    OrderViewSet,
    order_create,
    LatestProductsFeed,
    UserOrdersListView,
    export_user_orders_json,
)

app_name = "shopapp"

router = DefaultRouter()
router.register("products", ProductViewSet)
router.register("orders", OrderViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(router.urls)),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/latest/feed/", LatestProductsFeed(), name="products_feed"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path(
        "products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path(
        "users/<int:user_id>/orders/",
        UserOrdersListView.as_view(),
        name="user_orders_list",
    ),
    path(
        "users/<int:user_id>/orders/export/",
        export_user_orders_json,
        name="user_orders_export",
    ),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/create/", order_create, name="orders_create"),
]

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}
            Title Auth
        {% endblock %}
    </title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    {% block body %}
        block Auth
    {% endblock %}
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mysite/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
        <h1 class="h3 mb-3 fw-normal">
            Hi {{ user.username }}!
        </h1>
    <form action="{% url 'myauth:logout' %}" method="post">
        {% csrf_token %}
        <div class="d-grid gap-2 d-md-block mt-2 mb-3">
            <button type="submit" class="btn btn-primary py-2">Log Out</button>
        </div>
    </form>
    {% else %}
        <h3>You are not logged in</h3>
        <p class="mb-1">
            <a href="{% url 'myauth:login' %}">Log In</a>
        </p>
    {% endif %}
    <div class="mb-2">
        <a href="{% url 'myauth:register' %}">Register</a>
    </div>
    <div class="mb-2">
        <a href="{% url 'myauth:list_user' %}">List users</a>
    </div>
    <div class="mb-2">
        <a href="{% url 'shopapp:index' %}">Shop index</a>
    </div>
{% endblock %}