mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path


from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    AboutMeUpdateView,
    ListUsersView,
    UserDetailsView,
)

app_name = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path(
        "about-me/<int:pk>/update/", AboutMeUpdateView.as_view(), name="update_about_me"
    ),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/", ListUsersView.as_view(), name="list_user"),
    path("users/<int:pk>/", UserDetailsView.as_view(), name="user_details"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic.base import TemplateView
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from rest_framework.routers import DefaultRouter
from shopapp.views import (
    ProductViewSet,
    OrderViewSet,
)
from .sitemaps import sitemaps

router = DefaultRouter()
router.register("products", ProductViewSet)
router.register("orders", OrderViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shop/", include("shopapp.urls")),
    path("myauth/", include("myauth.urls")),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="docs"),
    # path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/", include(router.urls)),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path(
            "__debug__/",
            include(debug_toolbar.urls),
        )
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    ProductDetailsView,
    ProductsListView,
    OrdersListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    ProductViewSet,
    OrderViewSet,
    order_create,
    LatestProductsFeed,
    UserOrdersListView,
    export_user_orders_json,
)

app_name = "shopapp"

router = DefaultRouter()
router.register("products", ProductViewSet)
router.register("orders", OrderViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(router.urls)),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/latest/feed/", LatestProductsFeed(), name="products_feed"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path(
        "products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path(
        "users/<int:user_id>/orders/",
        UserOrdersListView.as_view(),
        name="user_orders_list",
    ),
    path(
        "users/<int:user_id>/orders/export/",
        export_user_orders_json,
        name="user_orders_export",
    ),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/create/", order_create, name="orders_create"),
]

mysite/shopapp/forms.py
from django import forms
from django.core.exceptions import ValidationError


from shopapp.models import Product, Order


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


def validate_price(value: int):
    if value < 0:
        msg = "the value must be greater than zero'"
        raise ValidationError(msg)


class ProductForm(forms.ModelForm):
    images = MultipleFileField(label="Select files", required=False)

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields["price"].validators = [validate_price]

    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview", "images"


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "delivery_address", "promocode", "user", "products"


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

mysite/shopapp/views.py
import logging
import json
from csv import DictWriter

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.cache import cache
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib.syndication.views import Feed
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import (
    extend_schema_view,
    extend_schema,
    OpenApiResponse,
    OpenApiExample,
)
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.request import Request
from rest_framework.parsers import MultiPartParser
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from .forms import ProductForm, OrderForm
from .common import save_csv_products
from .models import Product, Order, ProductImage
from .serializers import (
    ProductSerializer,
    OrderSerializer,
    DetailSerializer,
    OrderFullSerializer,
)

log = logging.getLogger(__name__)


class UserOrdersListView(LoginRequiredMixin, ListView):
    template_name = "shopapp/orders-list-users.html"

    def get_queryset(self):
        if self.kwargs["user_id"]:
            user_id: int = self.kwargs["user_id"]
        else:
            user_id: int = 1
        self.owner: User = get_object_or_404(User, pk=user_id)
        return (
            Order.objects.select_related("user")
            .prefetch_related("products")
            .filter(user=self.owner)
        )

    def get_context_data(self, **kwargs):
        log.info("Show orders list by user %s:", self.owner.username)
        context = super().get_context_data(**kwargs)
        context["username"] = self.owner.username
        context["user_id"] = self.owner.pk
        return context


def export_user_orders_json(request: Request, user_id: int):
    # проверка данных кеша по ключу
    cache_key = f"orders_data_{user_id}"
    orders_json = cache.get(cache_key)

    if orders_json is None:
        user: User = get_object_or_404(User, pk=user_id)

        queryset = (
            Order.objects.select_related("user")
            .prefetch_related("products")
            .filter(user=user)
            .order_by("pk")
        )
        serializer = OrderSerializer(queryset, many=True)
        orders_json = json.dumps(
            {"orders": serializer.data},
            indent=4,
        )

        # сохранение данных кеша по ключу
        cache.set("cache_key", orders_json, 300)

    # создаем файл с данными
    file_name = f"orders-export-{user_id}.json"
    with open(file_name, "w") as outfile:
        outfile.write(orders_json)

    # читаем файл для отправки клиенту
    file_name_out = "orders-export.json"
    with open(file_name, "r") as fh:
        response = HttpResponse(fh.read(), content_type="application/json")

    response["Content-Disposition"] = f"attachment; filename={file_name_out}"

    return response


@extend_schema(tags=["Products"])
@extend_schema_view(
    list=extend_schema(
        summary="Получить список имеющихся товаров",
    ),
    update=extend_schema(
        summary="Изменение товара",
        request=ProductSerializer,
        responses={
            status.HTTP_200_OK: ProductSerializer,
            status.HTTP_400_BAD_REQUEST: DetailSerializer,
            status.HTTP_500_INTERNAL_SERVER_ERROR: OpenApiResponse(
                response=None,
                description="Что-то пошло не так",
            ),
        },
        examples=[
            OpenApiExample(
                "Product example",
                description="Пример заполнения карточки товара",
                value={
                    "name": "New Product",
                    "description": "Info about new Product",
                    "price": "12.99",
                    "discount": 5,
                    "archived": False,
                    "preview": None,
                },
                status_codes=[str(status.HTTP_200_OK)],
            )
        ],
    ),
    partial_update=extend_schema(
        summary="Изменение данных в карточке товара",
        description="Возможно вносить частичные изменения в карточку товара",
    ),
    create=extend_schema(
        summary="Создание нового товара",
        request=ProductSerializer,
        responses={
            status.HTTP_200_OK: ProductSerializer,
            status.HTTP_400_BAD_REQUEST: DetailSerializer,
            status.HTTP_500_INTERNAL_SERVER_ERROR: OpenApiResponse(
                response=None,
                description="Что-то пошло не так",
            ),
        },
        examples=[
            OpenApiExample(
                "Product example",
                description="Пример заполнения карточки товара",
                value={
                    "name": "New Product",
                    "description": "Info about new Product",
                    "price": "12.99",
                    "discount": 5,
                    "archived": False,
                    "preview": None,
                },
                status_codes=[str(status.HTTP_200_OK)],
            )
        ],
    ),
    retrieve=extend_schema(
        summary="Детальная информация о товаре",
        responses={
            status.HTTP_200_OK: ProductSerializer,
            status.HTTP_400_BAD_REQUEST: DetailSerializer,
            status.HTTP_500_INTERNAL_SERVER_ERROR: OpenApiResponse(
                response=None,
                description="Что-то пошло не так",
            ),
        },
    ),
)
class ProductViewSet(ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    filter_backends = [
        SearchFilter,
        OrderingFilter,
    ]
    search_fields = [
        "name",
        "description",
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @extend_schema(
        summary="Архивирование товара",
    )
    def destroy(self, request, *args, **kwargs):
        isinstance = self.get_object()
        isinstance.archived = True
        isinstance.save()
        return Response(status=status.HTTP_204_NO_CONTENT)
        # return super().destroy(request, *args, **kwargs)

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        file_name = "products-export.csv"
        response["Content-Disposition"] = f"attachment; filename={file_name}"
        # Фильтрация результатов фильтрами, указанными в данном классе
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            "description",
            "price",
            "discount",
        ]
        # Загрузка только указанных полей
        queryset = queryset.only(*fields)

        # Записываем в response как в обычный файл
        writer = DictWriter(
            response,
            fieldnames=fields,
        )
        writer.writeheader()
        for product in queryset:
            writer.writerow({field: getattr(product, field) for field in fields})

        return response

    @action(methods=["post"], detail=False, parser_classes=[MultiPartParser])
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES["file"].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)


@extend_schema(tags=["Orders"])
@extend_schema_view(
    list=extend_schema(
        summary="Получить список имеющихся заказов",
        responses={
            status.HTTP_200_OK: OrderFullSerializer,
            status.HTTP_400_BAD_REQUEST: DetailSerializer,
            status.HTTP_500_INTERNAL_SERVER_ERROR: OpenApiResponse(
                response=None,
                description="Что-то пошло не так",
            ),
        },
    ),
    update=extend_schema(
        summary="Изменение заказа",
        request=OrderSerializer,
        responses={
            status.HTTP_200_OK: OrderSerializer,
            status.HTTP_400_BAD_REQUEST: DetailSerializer,
            status.HTTP_500_INTERNAL_SERVER_ERROR: OpenApiResponse(
                response=None,
                description="Что-то пошло не так",
            ),
        },
        examples=[
            OpenApiExample(
                "Order example",
                description="Пример создания заказа",
                value={
                    "delivery_address": "ul Mira 11",
                    "promocode": "SALE",
                    "user": 1,
                    "products": [1, 3],
                    "receipt": None,
                },
                status_codes=[str(status.HTTP_200_OK)],
            )
        ],
    ),
    partial_update=extend_schema(
        summary="Изменение данных в заказе",
        description="Возможно вносить частичные изменения в заказ",
    ),
    create=extend_schema(
        summary="Создание нового заказа",
        request=OrderSerializer,
        responses={
            status.HTTP_200_OK: ProductSerializer,
            status.HTTP_400_BAD_REQUEST: DetailSerializer,
            status.HTTP_500_INTERNAL_SERVER_ERROR: OpenApiResponse(
                response=None,
                description="Что-то пошло не так",
            ),
        },
        examples=[
            OpenApiExample(
                "Product example",

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends "shopapp/base.html" %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
<div>
    <h3>Form create order</h3>
</div>
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Submit</button>
    </form>
</div>

<div>
    <a href="{% url 'shopapp:orders_list' %}">Back to order list</a>
</div>

{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends "shopapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
<div>
    <h3 class="mb-1">Form create product</h3>
</div>
<div class="col-4">
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}

        <button type="submit" class="btn btn-primary py-2">Submit</button>
    </form>
</div>

<div class="mb-3">
    <a href="{% url 'shopapp:products_list' %}">Back to product list</a>
</div>

{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Groups List
{% endblock %}

{% block body %}
  <h1>Groups:</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
  {% if not groups %}
    <h3>No groups yet</h3>
  {% else %}
    <ul>

      {% for group in groups %}
          <li>
            <div>{{ group.name }}</div>
            <ul>
              {% for permission in group.permissions.all %}
                <li>
                  {{ permission.name }}
                  (<code>{{ permission.codename }}</code>)
                </li>
              {% endfor %}

            </ul>
          </li>
      {% endfor %}

    </ul>
  {% endif %}
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_changelist.html
{% extends 'admin/change_list.html' %}
{% load admin_urls %}

{% block object-tools-items %}
    <li>
        <a href="{% url 'admin:import_orders_csv' %}" class="addLink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order #{{ object.pk }} details
{% endblock %}

{% block body %}
  <h1>Order #{{ object.pk }}</h1>
  <div>
    <p>Order by {% firstof object.user.first_name object.user.username %}</p>
    <p>Promocode: <code>{{ object.promocode }}</code></p>
    <p>Delivery address: {{ object.delivery_address }}</p>
    <div>
      Product in order:
      <ul>
        {% for product in object.products.all %}
          <li>{{ product.name }} for ${{ product.price }}</li>
        {% endfor %}

      </ul>
    </div>
  </div>

  <div>
    <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if object_list %}
    <div>
      {% for order in object_list %}
        <div>
          <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
          >Details #{{ order.pk }}</a></p>
          <p>Order by {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{ order.promocode }}</code></p>
          <p>Delivery address: {{ order.delivery_address }}</p>
          <div>
            Product in order:
            <ul>
              {% for product in order.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}

            </ul>
          </div>

        </div>
      {% endfor %}

    </div>
  {% else %}
    <h3>No orders yet</h3>
  {% endif %}
  <div></div>
  <div>
    <a href="{% url 'shopapp:orders_create' %}"> Create order</a>
  </div>
  <div>
    <a href="{% url 'shopapp:index' %}">Back to index shop list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/orders-list-users.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
    Time running: {% now "u" %}
  {% if object_list %}
  <div>
      <h1>Пользователь {{ username }} выполнил следующие заказы:</h1>
  </div>
  {% cache 20 orders user_id%}
    <div>
      Time running(cache): {% now "u" %}
      {% for order in object_list %}
        <div>
          <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
          >Details #{{ order.pk }}</a></p>
          <p>Order by {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{ order.promocode }}</code></p>
          <p>Delivery address: {{ order.delivery_address }}</p>
          <div>
            Product in order:
            <ul>
              {% for product in order.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}

            </ul>
          </div>

        </div>
      {% endfor %}

    </div>
  {% endcache %}
  <div>
    <a href="{% url 'shopapp:user_orders_export' user_id=user_id%}">Export orders to the file</a>
  </div>
  {% else %}
    <h3>У пользователя {{ username }} ещё нет заказов</h3>
  {% endif %}
  <div></div>

  <div>
    <a href="{% url 'shopapp:orders_create' %}"> Create order</a>
  </div>
  <div>
    <a href="{% url 'shopapp:index' %}">Back to index shop list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_changelist.html
{% extends 'admin/change_list.html' %}
{% load admin_urls %}

{% block object-tools-items %}
    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addLink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to archive {{ object.name }}?</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:product_details' pk=object.pk %}"
    >Back to product</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Archive</button>
    </form>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create product</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}"
    >Back to products list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Product #{{ product.pk }}
{% endblock %}

{% block body %}
  <h1>Product <strong>{{ product.name }}</strong></h1>
  <div>
    <div>Description: <em>{{ product.description }}</em></div>
    <div>Price: {{ product.price }}</div>
    <div>Discount: {{ product.discount }}</div>
    <div>Archived: {{ product.archived }}</div>

    {% if product.preview %}
      <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
    {% endif %}

    <h3>Images:</h3>
    <div>
      {% for img in product.images.all %}
        <div>
          <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
          <div>{{ img.description }}</div>
        </div>
      {% empty %}
        <div>No images uploaded yet</div>
      {% endfor %}

    </div>
  </div>
  <div>
    <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
  </div>
  <div>
    <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archive product</a>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Products list
{% endblock %}

{% block body %}
  <h1>Products:</h1>
  {% if products %}
    <div>
    {% for product in products %}
      <div>
        <p><a href="{% url 'shopapp:product_details' pk=product.pk %}"
        >Name: {{ product.name }}</a></p>
        <p>Price: {{ product.price }}</p>
        <p>Discount: {% firstof product.discount 'no discount' %}</p>

        {% if product.preview %}
          <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}
      </div>
    {% endfor %}

    </div>

  {% else %}
    <h3>No products yet</h3>
  {% endif %}

  <div>
    <a href="{% url 'shopapp:product_create' %}"
      >Create a new product</a>
  </div>
  <div>
    <a href="{% url 'shopapp:index' %}">Back to index shop list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Shop Index
{% endblock %}


{% block body %}
  <h2 class="fw-light">Shop Index!</h2>

  <div>
    <ul>
      <li class="mb-2">
        <a href="{% url 'shopapp:products_list' %}">Products</a>
      </li>
      <li>
        <a href="{% url 'shopapp:orders_list' %}">Orders</a>
      </li>
       {% if user.is_authenticated %}
          <li>
            <a href="{% url 'shopapp:user_orders_list' user_id=request.user.pk%}">Orders by user</a>
          </li>
      {% endif %}
    </ul>
  </div>
  <div>
    <a href="{% url 'home' %}">Home page</a>
  </div>

{% endblock %}