mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path


from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    AboutMeUpdateView,
    ListUsersView,
    UserDetailsView,
)

app_name = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path(
        "about-me/<int:pk>/update/", AboutMeUpdateView.as_view(), name="update_about_me"
    ),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/", ListUsersView.as_view(), name="list_user"),
    path("users/<int:pk>/", UserDetailsView.as_view(), name="user_details"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic.base import TemplateView
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from rest_framework.routers import DefaultRouter
from shopapp.views import (
    ProductViewSet,
    OrderViewSet,
)
from .sitemaps import sitemaps

router = DefaultRouter()
router.register("products", ProductViewSet)
router.register("orders", OrderViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shop/", include("shopapp.urls")),
    path("myauth/", include("myauth.urls")),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="docs"),
    # path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/", include(router.urls)),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path(
            "__debug__/",
            include(debug_toolbar.urls),
        )
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    ProductDetailsView,
    ProductsListView,
    OrdersListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    ProductViewSet,
    OrderViewSet,
    order_create,
    LatestProductsFeed,
    UserOrdersListView,
    export_user_orders_json,
)

app_name = "shopapp"

router = DefaultRouter()
router.register("products", ProductViewSet)
router.register("orders", OrderViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(router.urls)),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/latest/feed/", LatestProductsFeed(), name="products_feed"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path(
        "products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path(
        "users/<int:user_id>/orders/",
        UserOrdersListView.as_view(),
        name="user_orders_list",
    ),
    path(
        "users/<int:user_id>/orders/export/",
        export_user_orders_json,
        name="user_orders_export",
    ),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/create/", order_create, name="orders_create"),
]

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def user_directory_path(instance, filename):
    return 'user_{pk}/{filename}'.format(pk=instance.user.id, filename=filename)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=user_directory_path)

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse

def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    class Meta:
        ordering = ["name", "price"]

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"

    def get_absolute_url(self):
        return reverse('shopapp:product_details', kwargs={"pk": self.pk})


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to='orders/receipts/')

mysite/myauth/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "bio", "avatar"

    # def __init__(self, *args, **kwargs):
    #     """
    #     Обновление стилей формы обновления
    #     """
    #     super().__init__(*args, **kwargs)
    #     for field in self.fields:
    #         self.fields[field].widget.attrs.update({
    #             'class': 'form-control',
    #             'autocomplete': 'off'
    #         })


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

    # def __init__(self, *args, **kwargs):
    #     """
    #     Обновление стилей формы под bootstrap
    #     """
    #     super().__init__(*args, **kwargs)
    #     for field in self.fields:
    #         self.fields[field].widget.attrs.update({
    #             'class': 'form-control',
    #             'autocomplete': 'off'
    #         })

    def clean_email(self):
        """
        Проверка email на уникальность
        """
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError('Email адрес должен быть уникальным')
        return email

mysite/myauth/views.py
import logging

from django.contrib.auth.decorators import (
    login_required,
    permission_required,
    user_passes_test,
)
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView
from django.db import transaction
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views import View
from django.shortcuts import reverse
from django.views.generic import (
    TemplateView,
    CreateView,
    UpdateView,
    ListView,
    DetailView,
)
from django.contrib.auth.mixins import (
    UserPassesTestMixin,
)

from .models import Profile
from .forms import ProfileForm, UserUpdateForm

log = logging.getLogger(__name__)


class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"

    def get_context_data(self, **kwargs):
        log.info("Show info about user")
        context = super().get_context_data(**kwargs)
        return context


class AboutMeUpdateView(UserPassesTestMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = "myauth/about-me_update_form.html"

    def test_func(self):
        log.debug("Сhecking user rights %s", self.request.user)
        return (
            self.get_object().user == self.request.user
        ) or self.request.user.is_staff

    def get_success_url(self):
        return reverse("myauth:user_details", kwargs={"pk": self.object.user.pk})

    def get_context_data(self, **kwargs):
        log.info("Update detail about user: %s", self.object.user.username)
        context = super().get_context_data(**kwargs)
        context["user_name"] = self.object.user.username
        if self.request.POST:
            context["user_form"] = UserUpdateForm(
                self.request.POST, instance=self.object.user
            )
        else:
            context["user_form"] = UserUpdateForm(instance=self.object.user)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        user_form = context["user_form"]
        with transaction.atomic():
            if all([form.is_valid(), user_form.is_valid()]):
                user_form.save()
                form.save()
            else:
                context.update({"user_form": user_form})
                return self.render_to_response(context)
        return super().form_valid(form)


class UserDetailsView(DetailView):
    log.info("Show detail about user")
    template_name = "myauth/about-me.html"
    model = User
    context_object_name = "user"

    def get_context_data(self, **kwargs):
        log.info("Get info about user %s", self.object.username)
        context = super().get_context_data(**kwargs)
        context["user_info"] = self.object.username
        return context


class ListUsersView(ListView):
    template_name = "myauth/users-list.html"
    context_object_name = "users"
    model = User

    def get_context_data(self, **kwargs):
        log.info("Show list users")
        context = super().get_context_data(**kwargs)
        return context


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        log.info("Register user")
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        log.debug("Login new user as %s", username)
        login(request=self.request, user=user)
        return response


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")

    def get_context_data(self, **kwargs):
        log.info("Logout user %s", self.request.user)
        context = super().get_context_data(**kwargs)
        return context


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
  About me
{% endblock %}


{% block body %}
  <h2>User info {{user_info}} </h2>
  {% if user.is_authenticated %}
    <h2>Detail</h2>
    <p>Username: {{ user.username }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Bio: {{ user.profile.bio }}</p>
    {% if user.profile.avatar %} 
      <div>
        <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
      </div>
    {% else %}
      <h3>Avatar not load</h3>
    {% endif %}
  {% else %}
    <h2>User is anonymous</h2>
  {% endif %}
  {% if user.profile.pk %}
    {% if request.user.is_staff or request.user.pk == user.pk %}
      <div>
        <a href="{% url 'myauth:update_about_me' pk=user.profile.pk %}">Update profile</a>
      </div>
    {% endif %}
  {% else %}
    <h3>The user does not have a profile</h3>
  {% endif %}
    <div class="mb-2">
        <a href="{% url 'home' %}">Back to start page</a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/about-me_update_form.html
{% extends 'myauth/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  About me
{% endblock %}


{% block body %}
  <div class="container">
      <h2>Update info about <i>{{ user_name }}</i> </h2>
  </div>

  {% if user.is_authenticated %}
  <div class="container">
    <div class="card mb-3 border-0 nth-shadow">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form | crispy }}
        {{ form | crispy}}
        <button type="submit" class="btn btn-primary py-2">Update</button>
      </form>
    </div>
  </div>
  {% else %}
    <h2>User is anonymous</h2>
  {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
      {% block title %}

      {% endblock %}
    </title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
{% block body %}

{% endblock %}
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-center-center">
            <div class="col-md-4 my-auto">
                <form method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-primary py-2">Log In</button>
                </form>
            </div>
        </div>
        <div class="pt-3">
            <a href="{% url 'home' %}">Back to start page</a>
        </div>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Register
{% endblock %}

{% block body %}
  <h1>Register</h1>
  <div class="col-md-4 my-auto">
    <form method="post">
      {% csrf_token %}
      {{ form | crispy }}
      <input type="submit" class="btn btn-primary py-2" value="Register">
    </form>
  </div>
{% endblock %}

mysite/myauth/templates/myauth/users-list.html
{% extends 'myauth/base.html' %}

{% block title %}
  Users list
{% endblock %}

{% block body %}
  <h1>Users:</h1>
  <div>
    {% for user in users %}
      <div>
        <p>Username: <a href="{% url 'myauth:user_details' pk=user.pk%}">{{ user.username }}</a></p>
      </div>
    {% endfor %}
  </div>

    <div class="mb-2">
        <a href="{% url 'home' %}">Bake to start page</a>
    </div>

<!--  {% if perms.shopapp.add_product %}-->
<!--    <div>-->
<!--      <a href="{% url 'shopapp:product_create' %}">Create a product</a>-->
<!--    </div>-->
<!--  {% endif %}-->
<!--  <div>-->
<!--    <p></p>-->
<!--    <a href="{% url 'shopapp:index' %}">Back to index shop list</a>-->
<!--  </div>-->
{% endblock %}